export enum ContractName {
    Orders = "0",
    ProviderRegistry = "1",
    Staking = "2",
    Superpro = "3",
    TeeOffersFactory = "4",
    Token = "5",
    ValueOffersFactory = "6",
    Voting = "7",
    Consensus = "8",
    Suspicious = "9",
    LastBlocks = "10",
    Epochs = "11",
}

export enum ParamName {
    OrderMinimumDeposit = "0",
    ProfitWithdrawDelayDays = "1",
    MinSecDeposit = "2",
    StakingPercentPerDay = "3",
    StopDelayDays = "4",
    TeeOfferSecDeposit = "5",
    OfferSecDeposit = "6",
    TeeRewardPerEpoch = "7",
    VotingDeposit = "8",
    VotingDurationDays = "9",
    VotingExecutionTimeoutDays = "10",
    VotingHoldDays = "11",
    VotingMinimumTurnout = "12",
    L1 = "13",
    L2 = "14",
    Threshold = "15",
    EpochDurationSeconds = "16",
}