# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
    push:
        branches: ['main']

jobs:
    build-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: https://npm.pkg.github.com/
                  scope: super-protocol
                  always-auth: true
            - run: yarn --frozen-lock --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_GH }}
            - run: yarn run docs
            - name: Setup SSH
              uses: MrSquaare/ssh-setup-action@v1
              with:
                  host: github.com
                  private-key: ${{ secrets.DEPLOY_KEY_GITHUB_DOCS }}
            - run: git clone git@github.com:Super-Protocol/docs.git temp-repo
            - run: cp -R ./auto-docs ./temp-repo/sdk-auto
            - name: Push to doc repo
              run: |
                  git add .
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"
                  git commit -m "update sdk docs automaticly"
                  git push
              working-directory: ./temp-repo
