# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Run unit tests on PR

on:
    pull_request:
        branches:
            - main
            - develop
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: 16
                scope: super-protocol
                always-auth: true
            - run: npm ci
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - run: npm run prepare
            - name: Check ESM build
              run: node -e "import('./dist/mjs/index.js')"
            - run: npm run test
